SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS ACCOUNT_TBL;
DROP TABLE IF EXISTS HIBERNATE_SEQUENCE;
DROP TABLE IF EXISTS USER_TBL;
DROP TABLE IF EXISTS USER_ACCOUNT;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE HIBERNATE_SEQUENCE (
   NEXT_VAL BIGINT
);

INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );

CREATE TABLE USER_TBL (
   ID_USER BIGINT NOT NULL,
    EMAIL_ADD VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PRIMARY KEY (ID_USER)
);

CREATE TABLE ACCOUNT_TBL (
   ID_ACCT BIGINT NOT NULL,
   NAME VARCHAR(255),
   CURR_BAL DECIMAL(19,2),
   PRIMARY KEY (ID_ACCT)
);

CREATE TABLE USER_ACCOUNT (
    ACCT_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PRIMARY KEY (ACCT_ID, USER_ID),
	CONSTRAINT ACCT_ID_FK FOREIGN KEY (ACCT_ID)  REFERENCES ACCOUNT_TBL (ID_ACCT),
	CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID)  REFERENCES USER_TBL (ID_USER)
);

