DROP TABLE IF EXISTS CREDENTIAL_TBL;
DROP TABLE IF EXISTS HIBERNATE_SEQUENCE;
DROP TABLE IF EXISTS USER_TBL;

CREATE TABLE HIBERNATE_SEQUENCE (
   NEXT_VAL BIGINT
);

INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );

CREATE TABLE USER_TBL (
   ID_USER BIGINT NOT NULL,
    EMAIL_ADD VARCHAR(255),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    PRIMARY KEY (ID_USER)
);

CREATE TABLE CREDENTIAL_TBL (
   ID_CREDENTIAL BIGINT NOT NULL,
   PASSWORD VARCHAR(255),
   USER_NAME VARCHAR(255),
   USER_ID BIGINT,
   PRIMARY KEY (ID_CREDENTIAL),
   CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID)  REFERENCES USER_TBL (ID_USER)
);