SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS HIBERNATE_SEQUENCE;
DROP TABLE IF EXISTS ACCOUNT_TBL;
DROP TABLE IF EXISTS TRANSACTION_TBL;
DROP TABLE IF EXISTS BUDGET_TBL;
DROP TABLE IF EXISTS BUDGET_TRANSACTION;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE HIBERNATE_SEQUENCE (
   NEXT_VAL BIGINT
);

INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );
INSERT INTO HIBERNATE_SEQUENCE VALUES ( 1 );

CREATE TABLE ACCOUNT_TBL (
   ID_ACCT BIGINT NOT NULL,
   NAME VARCHAR(255),
   CURR_BAL DECIMAL(19,2),
   PRIMARY KEY (ID_ACCT)
);

CREATE TABLE TRANSACTION_TBL (
   ID_TRANS BIGINT NOT NULL,
   ACCT_ID BIGINT NOT NULL,
   AMOUNT DECIMAL(19,2),
   NOTES VARCHAR(255),
   TRAN_TYPE VARCHAR(255),
   PRIMARY KEY (ID_TRANS),
   CONSTRAINT ACCT_ID_FK FOREIGN KEY (ACCT_ID)  REFERENCES ACCOUNT_TBL (ID_ACCT)
);

CREATE TABLE BUDGET_TBL (
	ID_BUDGET BIGINT NOT NULL,
	AMOUNT DECIMAL(19,2),
	NAME VARCHAR(255),
	PRIMARY KEY (ID_BUDGET)
);

CREATE TABLE BUDGET_TRANSACTION (
	BUDGET_ID BIGINT NOT NULL,
	TRANS_ID BIGINT NOT NULL,
	CONSTRAINT TRANS_ID_UK UNIQUE (TRANS_ID),
	CONSTRAINT BUDGET_ID_FK FOREIGN KEY (BUDGET_ID)  REFERENCES BUDGET_TBL (ID_BUDGET),
	CONSTRAINT TRANS_ID_FK FOREIGN KEY (TRANS_ID)  REFERENCES TRANSACTION_TBL (ID_TRANS)
)



